version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:26.2
    container_name: clickhouse-server
    hostname: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./import:/var/lib/clickhouse/user_files/import
      # - ./config/users.d/custom_settings.xml:/etc/clickhouse-server/users.d/custom_settings.xml
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=secret_password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s  # Увеличили время на старт
    restart: unless-stopped

volumes:
  clickhouse_data:
  clickhouse_logs: